token: 5092389819:AAHwEkqr5Qbn5eVaPg6LGuVqOU4r6xYC_a8

timeout: 3000

dials:

- name: ETC
  path: https://www.ethercluster.com/etc

- name: ETH
  path: https://mainnet.infura.io/v3/937680680cea4809b815db1d8d7b1d28

- name: DeHive
  path: https://polygon-rpc.com/

- name: FTM
  path: https://rpc.ftm.tools/

