token: 5092389819:AAE3Ojh80vNNOeJjz6jHW4ZtoN7B5OBEQMo

timeout: 3000

dials:
- name: ETC
  path: https://www.ethercluster.com/etc

- name: ETH
  path: https://mainnet.infura.io/v3/937680680cea4809b815db1d8d7b1d28

- name: DeHive
  path: https://polygon-rpc.com/